//! Custom bulk-action routing.
//!
//! Bulk actions are registered on the [`ActixAdminBuilder`] via
//! [`add_bulk_action_for_entity`]; the handler is a plain closure that
//! receives the current DB connection, the list of selected ids and the
//! tenant reference (if any), and returns a human-readable message shown
//! as a flash notification on the redirected list page.
//!
//! Wire-up:
//! * The list page's actions dropdown renders one entry per registered
//!   bulk action.
//! * On click, the ids from the table's checkbox form are POSTed to
//!   `/{entity}/action/{name}` with the CSRF token attached.
//! * The route handler dispatches to the registered closure via
//!   `Entity::run_bulk_action` (generated by the derive macro).
//!
//! [`add_bulk_action_for_entity`]: crate::builder::ActixAdminBuilderTrait::add_bulk_action_for_entity

use axum::extract::{Path, RawQuery};
use axum::http::{header, HeaderMap, StatusCode};
use axum::response::{IntoResponse, Response};
use axum::{Extension, Form};
use sea_orm::DatabaseConnection;
use std::sync::Arc;
use tower_sessions::Session;

use crate::admin_prelude;
use crate::prelude::*;

use super::helpers::run_local;
use super::RoutePrelude;

/// Dispatch trait implemented per entity to route named bulk actions to
/// their concrete handlers. Add a manual `impl` to your entity:
///
/// ```ignore
/// #[actix_admin::prelude::async_trait(?Send)]
/// impl actix_admin::routes::ActixAdminBulkActionDispatch for post::Entity {
///     async fn run_bulk_action(
///         name: &str,
///         db: &sea_orm::DatabaseConnection,
///         ids: Vec<Self::Id>,
///         tenant_ref: Option<i32>,
///     ) -> Result<Option<String>, ActixAdminError> {
///         match name {
///             "mark_reviewed" => Ok(Some(format!("reviewed {}", ids.len()))),
///             _ => Ok(None),
///         }
///     }
/// }
/// ```
#[async_trait::async_trait(?Send)]
pub trait ActixAdminBulkActionDispatch: ActixAdminViewModelTrait {
    /// Execute the bulk action named `name` against `ids`. Returning
    /// `Ok(None)` means "no such action registered for this entity".
    async fn run_bulk_action(
        _name: &str,
        _db: &DatabaseConnection,
        _ids: Vec<Self::Id>,
        _tenant_ref: Option<i32>,
    ) -> Result<Option<String>, ActixAdminError> {
        Ok(None)
    }
}

/// HTTP handler for `POST /{entity}/action/{name}`.
pub async fn bulk_action<E: ActixAdminBulkActionDispatch + 'static>(
    session: Session,
    headers: HeaderMap,
    RawQuery(raw_query): RawQuery,
    Extension(actix_admin): Extension<Arc<ActixAdmin>>,
    Extension(db): Extension<DatabaseConnection>,
    Path(action_name): Path<String>,
    Form(form): Form<Vec<(String, String)>>,
) -> Result<Response, ActixAdminError> {
    run_local(bulk_action_inner::<E>(
        session,
        headers,
        raw_query,
        actix_admin,
        db,
        action_name,
        form,
    ))
}

async fn bulk_action_inner<E: ActixAdminBulkActionDispatch + 'static>(
    session: Session,
    headers: HeaderMap,
    raw_query: Option<String>,
    actix_admin: Arc<ActixAdmin>,
    db: DatabaseConnection,
    action_name: String,
    form: Vec<(String, String)>,
) -> Result<Response, ActixAdminError> {
    let actix_admin = &actix_admin;
    let raw_query = raw_query.unwrap_or_default();
    let ctx = admin_prelude!(
        &session,
        &headers,
        &raw_query,
        actix_admin,
        RoutePrelude::bulk(),
        E
    );

    if !ctx
        .view_model
        .bulk_actions
        .iter()
        .any(|a| a.name == action_name)
    {
        return Ok((StatusCode::NOT_FOUND, "unknown bulk action").into_response());
    }

    let ids: Vec<E::Id> = form
        .iter()
        .filter_map(|(k, v)| (k == "ids").then(|| v.parse::<E::Id>().ok()).flatten())
        .collect();

    let db = &db;
    let result = E::run_bulk_action(&action_name, db, ids, ctx.tenant_ref).await;

    match result {
        Ok(Some(_msg)) => {
            // On success, bounce back to the entity's list page. We don't
            // yet have a flash-message channel; the message returned by the
            // handler is logged for observability.
            log::info!(target: "actix_admin::bulk_action", "{}/{action_name}: {_msg}", ctx.entity_name);
            Ok((
                StatusCode::SEE_OTHER,
                [(
                    header::LOCATION,
                    format!(
                        "{}/{}/list",
                        actix_admin.configuration.base_path, ctx.entity_name
                    ),
                )],
            )
                .into_response())
        }
        Ok(None) => Ok((StatusCode::NOT_FOUND, "unknown bulk action").into_response()),
        Err(e) => Err(e),
    }
}
